# -*- coding: utf-8 -*-
"""Practice_1_PP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UAHx6rV6TI8jMbmW8yxDPTIwk_rWSKID

TUGAS PRAKTIKUM 1
**PENGENALAN PYTHON**

# Vector
"""

import numpy as np

print('vektor default python\n')
an = np.arange(1,20,1)
bn = np.arange(1,20,2)

print(an)
print(bn)
print(an.ndim)
print(an.shape)

print('\n vektor via numpy \n')

#vektor via numpy
c = np.array([1,2,3,4,5])
d = np.array([1.5,2.5,5,6,7])

print(c)
print(d)

"""# Matrix"""

#mengubah dari 1D menjadi matriks 2D
a = np.arange(1,21,1)
c = a.reshape((4,5))
print(c)

"""# List
List merupakan representasi struktur data yang dapat menyimpan data dengan nilai numerik, karakter, dan lain-lain secara bersamaan
"""

list1 =["apple", "banana", "cherry"]
list2 = [1,5,7,9,3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]

print(list1)
print(list4)

"""# Data Frame
Spesialisasi dari tipe list untuk menyimpan vektor ke dalam bentuk frame (menyerupai basis data). Kelebihan dari matriks adalah dapat dimanipulasi dalam berbagai bentuk dan cara
"""

import pandas as pd

df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]), columns =['a','b','c'])
print(df)

"""# Import dan Export Data Serta Manipulasinya



"""

#membaca data dari file dengan format csv
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/input/data.csv', sep=',')
print(data)

#membaca data dari file dengan format text (delimeter)
print("\n Read Text Data with Tab Delimiter")
with open('/content/drive/MyDrive/Colab Notebooks/input/data.txt') as data :
  print(data.read())

#membaca data dari URL
f = pd.read_csv('http://www.exploredata.net/ftp/Spellman.csv')
print(f)

"""# TUGAS 1"""

import numpy as sp
import pandas as pd
import matplotlib.pyplot as plt

traffic = sp.genfromtxt("https://raw.githubusercontent.com/aricarmona/machine-learning-python/master/data/web_traffic.tsv", delimiter='\t')
#traffic.to_csv('/content/drive/MyDrive/Colab Notebooks/input/traffic.tsv', sep='\t')
#pd.DataFrame(traffic).to_txt('/content/drive/MyDrive/Colab Notebooks/input/traffic.tsv')
#mengambil sepuluh data pertama
print(traffic[:10])

#mengetahui size data [baris,kolom]
print(traffic.shape)

x = traffic[:,0]
y = traffic[:,1]

#mengambil nilai x yang kolom y tidak Nan
x = x[~sp.isnan(y)]
#mengambil nilai y yang tidak Nan
y = y[~sp.isnan(y)]

print(x.shape)
#menampilkan plot bentuk scatter
plt.scatter(x,y)
plt.title("Web Traffic Last Month")
plt.xlabel("Time")
plt.ylabel("Hits/Hours")

#pengelompkan berdasarkan waktu
plt.xticks([w*7*24 for w in range(10)],['week %i' %w for w in range(10)])

"""# **TUGAS 2**
Mempelajari pengelahan gambar menggunakan python serta menyimpan semua pekerjaan di repository github

"""

#operasi image pada python
#menggunakan library open cv
import cv2
import numpy as np
import matplotlib.pyplot as plt

print("read images using opencv")
five = cv2.imread('5.png') 
#menampilkan ukuran image, height width channels
print(five.shape)
#menampilkan banyaknya nilai matriks 141*144*3
print(five.size)
#menampilkan gambar
plt.imshow(five)
#menampilkan gambar sampai ada tombol keyboard di tekan
cv2.waitKey(0)

"""# *CONVERT IMAGE*"""

import cv2
babon = cv2.imread("logo IPB.png")
babon_gray = cv2.cvtColor(babon, cv2.COLOR_BGR2GRAY)

plt.imshow(babon)

fig = plt.figure()
ax1 = fig.add_subplot(1,2,1)
ax1.imshow(babon)
ax1.set_title('original')
ax2 = fig.add_subplot(1,2,2)
ax2.imshow(babon_gray)
ax2.set_title('convert to gray')

"""**Mengambl nilai matriks**

mengakses nilai piksel berdasarkan posisi image
"""

piksel = five[100,100]
print(piksel)
